// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: g2ssadm.proto

package g2ssadm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearLastExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLastExceptionRequest) Reset() {
	*x = ClearLastExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLastExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLastExceptionRequest) ProtoMessage() {}

func (x *ClearLastExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLastExceptionRequest.ProtoReflect.Descriptor instead.
func (*ClearLastExceptionRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{0}
}

type ClearLastExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLastExceptionResponse) Reset() {
	*x = ClearLastExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLastExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLastExceptionResponse) ProtoMessage() {}

func (x *ClearLastExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLastExceptionResponse.ProtoReflect.Descriptor instead.
func (*ClearLastExceptionResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{1}
}

type CreateSaltInStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoPin  string `protobuf:"bytes,1,opt,name=soPin,proto3" json:"soPin,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *CreateSaltInStoreRequest) Reset() {
	*x = CreateSaltInStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaltInStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaltInStoreRequest) ProtoMessage() {}

func (x *CreateSaltInStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaltInStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateSaltInStoreRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSaltInStoreRequest) GetSoPin() string {
	if x != nil {
		return x.SoPin
	}
	return ""
}

func (x *CreateSaltInStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSaltInStoreRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CreateSaltInStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateSaltInStoreResponse) Reset() {
	*x = CreateSaltInStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaltInStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaltInStoreResponse) ProtoMessage() {}

func (x *CreateSaltInStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaltInStoreResponse.ProtoReflect.Descriptor instead.
func (*CreateSaltInStoreResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSaltInStoreResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{4}
}

type DestroyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{5}
}

type GetLastExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLastExceptionRequest) Reset() {
	*x = GetLastExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionRequest) ProtoMessage() {}

func (x *GetLastExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionRequest.ProtoReflect.Descriptor instead.
func (*GetLastExceptionRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{6}
}

type GetLastExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetLastExceptionResponse) Reset() {
	*x = GetLastExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionResponse) ProtoMessage() {}

func (x *GetLastExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionResponse.ProtoReflect.Descriptor instead.
func (*GetLastExceptionResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastExceptionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetLastExceptionCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLastExceptionCodeRequest) Reset() {
	*x = GetLastExceptionCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionCodeRequest) ProtoMessage() {}

func (x *GetLastExceptionCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionCodeRequest.ProtoReflect.Descriptor instead.
func (*GetLastExceptionCodeRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{8}
}

type GetLastExceptionCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetLastExceptionCodeResponse) Reset() {
	*x = GetLastExceptionCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionCodeResponse) ProtoMessage() {}

func (x *GetLastExceptionCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionCodeResponse.ProtoReflect.Descriptor instead.
func (*GetLastExceptionCodeResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{9}
}

func (x *GetLastExceptionCodeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName     string `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	IniParams      string `protobuf:"bytes,2,opt,name=iniParams,proto3" json:"iniParams,omitempty"`
	VerboseLogging int32  `protobuf:"varint,3,opt,name=verboseLogging,proto3" json:"verboseLogging,omitempty"`
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{10}
}

func (x *InitRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *InitRequest) GetIniParams() string {
	if x != nil {
		return x.IniParams
	}
	return ""
}

func (x *InitRequest) GetVerboseLogging() int32 {
	if x != nil {
		return x.VerboseLogging
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{11}
}

type InitializeNewTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultSOPin string `protobuf:"bytes,1,opt,name=defaultSOPin,proto3" json:"defaultSOPin,omitempty"`
	NewSOPin     string `protobuf:"bytes,2,opt,name=newSOPin,proto3" json:"newSOPin,omitempty"`
	Label        string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *InitializeNewTokenRequest) Reset() {
	*x = InitializeNewTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeNewTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeNewTokenRequest) ProtoMessage() {}

func (x *InitializeNewTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeNewTokenRequest.ProtoReflect.Descriptor instead.
func (*InitializeNewTokenRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{12}
}

func (x *InitializeNewTokenRequest) GetDefaultSOPin() string {
	if x != nil {
		return x.DefaultSOPin
	}
	return ""
}

func (x *InitializeNewTokenRequest) GetNewSOPin() string {
	if x != nil {
		return x.NewSOPin
	}
	return ""
}

func (x *InitializeNewTokenRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type InitializeNewTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeNewTokenResponse) Reset() {
	*x = InitializeNewTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeNewTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeNewTokenResponse) ProtoMessage() {}

func (x *InitializeNewTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeNewTokenResponse.ProtoReflect.Descriptor instead.
func (*InitializeNewTokenResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{13}
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{14}
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{15}
}

func (x *ListResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoPin string `protobuf:"bytes,1,opt,name=soPin,proto3" json:"soPin,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{16}
}

func (x *PutRequest) GetSoPin() string {
	if x != nil {
		return x.SoPin
	}
	return ""
}

func (x *PutRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{17}
}

type ReinitializeTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoPin string `protobuf:"bytes,1,opt,name=soPin,proto3" json:"soPin,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *ReinitializeTokenRequest) Reset() {
	*x = ReinitializeTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReinitializeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReinitializeTokenRequest) ProtoMessage() {}

func (x *ReinitializeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReinitializeTokenRequest.ProtoReflect.Descriptor instead.
func (*ReinitializeTokenRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{18}
}

func (x *ReinitializeTokenRequest) GetSoPin() string {
	if x != nil {
		return x.SoPin
	}
	return ""
}

func (x *ReinitializeTokenRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ReinitializeTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReinitializeTokenResponse) Reset() {
	*x = ReinitializeTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReinitializeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReinitializeTokenResponse) ProtoMessage() {}

func (x *ReinitializeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReinitializeTokenResponse.ProtoReflect.Descriptor instead.
func (*ReinitializeTokenResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{19}
}

type SetupStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoPin string `protobuf:"bytes,1,opt,name=soPin,proto3" json:"soPin,omitempty"`
}

func (x *SetupStoreRequest) Reset() {
	*x = SetupStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupStoreRequest) ProtoMessage() {}

func (x *SetupStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupStoreRequest.ProtoReflect.Descriptor instead.
func (*SetupStoreRequest) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{20}
}

func (x *SetupStoreRequest) GetSoPin() string {
	if x != nil {
		return x.SoPin
	}
	return ""
}

type SetupStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetupStoreResponse) Reset() {
	*x = SetupStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2ssadm_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupStoreResponse) ProtoMessage() {}

func (x *SetupStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2ssadm_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupStoreResponse.ProtoReflect.Descriptor instead.
func (*SetupStoreResponse) Descriptor() ([]byte, []int) {
	return file_g2ssadm_proto_rawDescGZIP(), []int{21}
}

var File_g2ssadm_proto protoreflect.FileDescriptor

var file_g2ssadm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x61,
	0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c,
	0x74, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x6f, 0x50, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x6f, 0x50, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0x33, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x74, 0x49,
	0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73,
	0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x73, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x26,
	0x0a, 0x0e, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x0e, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x4f,
	0x50, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x53, 0x4f, 0x50, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x4f,
	0x50, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x4f,
	0x50, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x1c, 0x0a, 0x1a, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4e,
	0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x6f, 0x50, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6f, 0x50,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0d,
	0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a,
	0x18, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x50,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6f, 0x50, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x50, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6f, 0x50, 0x69, 0x6e, 0x22, 0x14, 0x0a,
	0x12, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xf4, 0x06, 0x0a, 0x07, 0x47, 0x32, 0x53, 0x73, 0x61, 0x64, 0x6d, 0x12,
	0x5f, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x32, 0x73, 0x73,
	0x61, 0x64, 0x6d, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63,
	0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x74, 0x49, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x74, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61,
	0x64, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x74, 0x49, 0x6e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x17, 0x2e, 0x67, 0x32, 0x73, 0x73,
	0x61, 0x64, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x24, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61,
	0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x2e,
	0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x32, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x13, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d,
	0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x32,
	0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61,
	0x64, 0x6d, 0x2e, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x32,
	0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x1a, 0x2e, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x32,
	0x73, 0x73, 0x61, 0x64, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6e, 0x7a, 0x69, 0x6e, 0x67,
	0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x32, 0x73, 0x73, 0x61, 0x64, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_g2ssadm_proto_rawDescOnce sync.Once
	file_g2ssadm_proto_rawDescData = file_g2ssadm_proto_rawDesc
)

func file_g2ssadm_proto_rawDescGZIP() []byte {
	file_g2ssadm_proto_rawDescOnce.Do(func() {
		file_g2ssadm_proto_rawDescData = protoimpl.X.CompressGZIP(file_g2ssadm_proto_rawDescData)
	})
	return file_g2ssadm_proto_rawDescData
}

var file_g2ssadm_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_g2ssadm_proto_goTypes = []interface{}{
	(*ClearLastExceptionRequest)(nil),    // 0: g2ssadm.ClearLastExceptionRequest
	(*ClearLastExceptionResponse)(nil),   // 1: g2ssadm.ClearLastExceptionResponse
	(*CreateSaltInStoreRequest)(nil),     // 2: g2ssadm.CreateSaltInStoreRequest
	(*CreateSaltInStoreResponse)(nil),    // 3: g2ssadm.CreateSaltInStoreResponse
	(*DestroyRequest)(nil),               // 4: g2ssadm.DestroyRequest
	(*DestroyResponse)(nil),              // 5: g2ssadm.DestroyResponse
	(*GetLastExceptionRequest)(nil),      // 6: g2ssadm.GetLastExceptionRequest
	(*GetLastExceptionResponse)(nil),     // 7: g2ssadm.GetLastExceptionResponse
	(*GetLastExceptionCodeRequest)(nil),  // 8: g2ssadm.GetLastExceptionCodeRequest
	(*GetLastExceptionCodeResponse)(nil), // 9: g2ssadm.GetLastExceptionCodeResponse
	(*InitRequest)(nil),                  // 10: g2ssadm.InitRequest
	(*InitResponse)(nil),                 // 11: g2ssadm.InitResponse
	(*InitializeNewTokenRequest)(nil),    // 12: g2ssadm.InitializeNewTokenRequest
	(*InitializeNewTokenResponse)(nil),   // 13: g2ssadm.InitializeNewTokenResponse
	(*ListRequest)(nil),                  // 14: g2ssadm.ListRequest
	(*ListResponse)(nil),                 // 15: g2ssadm.ListResponse
	(*PutRequest)(nil),                   // 16: g2ssadm.PutRequest
	(*PutResponse)(nil),                  // 17: g2ssadm.PutResponse
	(*ReinitializeTokenRequest)(nil),     // 18: g2ssadm.ReinitializeTokenRequest
	(*ReinitializeTokenResponse)(nil),    // 19: g2ssadm.ReinitializeTokenResponse
	(*SetupStoreRequest)(nil),            // 20: g2ssadm.SetupStoreRequest
	(*SetupStoreResponse)(nil),           // 21: g2ssadm.SetupStoreResponse
}
var file_g2ssadm_proto_depIdxs = []int32{
	0,  // 0: g2ssadm.G2Ssadm.ClearLastException:input_type -> g2ssadm.ClearLastExceptionRequest
	2,  // 1: g2ssadm.G2Ssadm.CreateSaltInStore:input_type -> g2ssadm.CreateSaltInStoreRequest
	4,  // 2: g2ssadm.G2Ssadm.Destroy:input_type -> g2ssadm.DestroyRequest
	6,  // 3: g2ssadm.G2Ssadm.GetLastException:input_type -> g2ssadm.GetLastExceptionRequest
	8,  // 4: g2ssadm.G2Ssadm.GetLastExceptionCode:input_type -> g2ssadm.GetLastExceptionCodeRequest
	10, // 5: g2ssadm.G2Ssadm.Init:input_type -> g2ssadm.InitRequest
	12, // 6: g2ssadm.G2Ssadm.InitializeNewToken:input_type -> g2ssadm.InitializeNewTokenRequest
	14, // 7: g2ssadm.G2Ssadm.List:input_type -> g2ssadm.ListRequest
	16, // 8: g2ssadm.G2Ssadm.Put:input_type -> g2ssadm.PutRequest
	18, // 9: g2ssadm.G2Ssadm.ReinitializeToken:input_type -> g2ssadm.ReinitializeTokenRequest
	20, // 10: g2ssadm.G2Ssadm.SetupStore:input_type -> g2ssadm.SetupStoreRequest
	1,  // 11: g2ssadm.G2Ssadm.ClearLastException:output_type -> g2ssadm.ClearLastExceptionResponse
	3,  // 12: g2ssadm.G2Ssadm.CreateSaltInStore:output_type -> g2ssadm.CreateSaltInStoreResponse
	5,  // 13: g2ssadm.G2Ssadm.Destroy:output_type -> g2ssadm.DestroyResponse
	7,  // 14: g2ssadm.G2Ssadm.GetLastException:output_type -> g2ssadm.GetLastExceptionResponse
	9,  // 15: g2ssadm.G2Ssadm.GetLastExceptionCode:output_type -> g2ssadm.GetLastExceptionCodeResponse
	11, // 16: g2ssadm.G2Ssadm.Init:output_type -> g2ssadm.InitResponse
	13, // 17: g2ssadm.G2Ssadm.InitializeNewToken:output_type -> g2ssadm.InitializeNewTokenResponse
	15, // 18: g2ssadm.G2Ssadm.List:output_type -> g2ssadm.ListResponse
	17, // 19: g2ssadm.G2Ssadm.Put:output_type -> g2ssadm.PutResponse
	19, // 20: g2ssadm.G2Ssadm.ReinitializeToken:output_type -> g2ssadm.ReinitializeTokenResponse
	21, // 21: g2ssadm.G2Ssadm.SetupStore:output_type -> g2ssadm.SetupStoreResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_g2ssadm_proto_init() }
func file_g2ssadm_proto_init() {
	if File_g2ssadm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_g2ssadm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLastExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLastExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaltInStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaltInStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeNewTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeNewTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReinitializeTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReinitializeTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2ssadm_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_g2ssadm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_g2ssadm_proto_goTypes,
		DependencyIndexes: file_g2ssadm_proto_depIdxs,
		MessageInfos:      file_g2ssadm_proto_msgTypes,
	}.Build()
	File_g2ssadm_proto = out.File
	file_g2ssadm_proto_rawDesc = nil
	file_g2ssadm_proto_goTypes = nil
	file_g2ssadm_proto_depIdxs = nil
}
