// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: g2hasher.proto

package g2hasher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearLastExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLastExceptionRequest) Reset() {
	*x = ClearLastExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLastExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLastExceptionRequest) ProtoMessage() {}

func (x *ClearLastExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLastExceptionRequest.ProtoReflect.Descriptor instead.
func (*ClearLastExceptionRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{0}
}

type ClearLastExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearLastExceptionResponse) Reset() {
	*x = ClearLastExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearLastExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLastExceptionResponse) ProtoMessage() {}

func (x *ClearLastExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLastExceptionResponse.ProtoReflect.Descriptor instead.
func (*ClearLastExceptionResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{1}
}

type DestroyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{2}
}

type DestroyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{3}
}

type ExportTokenLibraryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportTokenLibraryRequest) Reset() {
	*x = ExportTokenLibraryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTokenLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTokenLibraryRequest) ProtoMessage() {}

func (x *ExportTokenLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTokenLibraryRequest.ProtoReflect.Descriptor instead.
func (*ExportTokenLibraryRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{4}
}

type ExportTokenLibraryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ExportTokenLibraryResponse) Reset() {
	*x = ExportTokenLibraryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTokenLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTokenLibraryResponse) ProtoMessage() {}

func (x *ExportTokenLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTokenLibraryResponse.ProtoReflect.Descriptor instead.
func (*ExportTokenLibraryResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{5}
}

func (x *ExportTokenLibraryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetLastExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLastExceptionRequest) Reset() {
	*x = GetLastExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionRequest) ProtoMessage() {}

func (x *GetLastExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionRequest.ProtoReflect.Descriptor instead.
func (*GetLastExceptionRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{6}
}

type GetLastExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetLastExceptionResponse) Reset() {
	*x = GetLastExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionResponse) ProtoMessage() {}

func (x *GetLastExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionResponse.ProtoReflect.Descriptor instead.
func (*GetLastExceptionResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastExceptionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetLastExceptionCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLastExceptionCodeRequest) Reset() {
	*x = GetLastExceptionCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionCodeRequest) ProtoMessage() {}

func (x *GetLastExceptionCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionCodeRequest.ProtoReflect.Descriptor instead.
func (*GetLastExceptionCodeRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{8}
}

type GetLastExceptionCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigID int32 `protobuf:"varint,1,opt,name=configID,proto3" json:"configID,omitempty"`
}

func (x *GetLastExceptionCodeResponse) Reset() {
	*x = GetLastExceptionCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastExceptionCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastExceptionCodeResponse) ProtoMessage() {}

func (x *GetLastExceptionCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastExceptionCodeResponse.ProtoReflect.Descriptor instead.
func (*GetLastExceptionCodeResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{9}
}

func (x *GetLastExceptionCodeResponse) GetConfigID() int32 {
	if x != nil {
		return x.ConfigID
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName     string `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	IniParams      string `protobuf:"bytes,2,opt,name=iniParams,proto3" json:"iniParams,omitempty"`
	VerboseLogging int32  `protobuf:"varint,3,opt,name=verboseLogging,proto3" json:"verboseLogging,omitempty"`
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{10}
}

func (x *InitRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *InitRequest) GetIniParams() string {
	if x != nil {
		return x.IniParams
	}
	return ""
}

func (x *InitRequest) GetVerboseLogging() int32 {
	if x != nil {
		return x.VerboseLogging
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{11}
}

type InitWithConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName     string `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	IniParams      string `protobuf:"bytes,2,opt,name=iniParams,proto3" json:"iniParams,omitempty"`
	ConfigJson     string `protobuf:"bytes,3,opt,name=configJson,proto3" json:"configJson,omitempty"`
	VerboseLogging int32  `protobuf:"varint,4,opt,name=verboseLogging,proto3" json:"verboseLogging,omitempty"`
}

func (x *InitWithConfigRequest) Reset() {
	*x = InitWithConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitWithConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWithConfigRequest) ProtoMessage() {}

func (x *InitWithConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWithConfigRequest.ProtoReflect.Descriptor instead.
func (*InitWithConfigRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{12}
}

func (x *InitWithConfigRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *InitWithConfigRequest) GetIniParams() string {
	if x != nil {
		return x.IniParams
	}
	return ""
}

func (x *InitWithConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *InitWithConfigRequest) GetVerboseLogging() int32 {
	if x != nil {
		return x.VerboseLogging
	}
	return 0
}

type InitWithConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitWithConfigResponse) Reset() {
	*x = InitWithConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitWithConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWithConfigResponse) ProtoMessage() {}

func (x *InitWithConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWithConfigResponse.ProtoReflect.Descriptor instead.
func (*InitWithConfigResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{13}
}

type ProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record string `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessRequest) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_g2hasher_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_g2hasher_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_g2hasher_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_g2hasher_proto protoreflect.FileDescriptor

var file_g2hasher_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x1a, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x19, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1d, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x22, 0x73, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x76, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x0e, 0x0a, 0x0c,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9d, 0x01, 0x0a,
	0x15, 0x49, 0x6e, 0x69, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4a, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x76, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x18, 0x0a, 0x16,
	0x49, 0x6e, 0x69, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0x29, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xaa, 0x05, 0x0a, 0x08,
	0x47, 0x32, 0x48, 0x61, 0x73, 0x68, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x4c,
	0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x18, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a,
	0x12, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67,
	0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x45,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x15,
	0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1f, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x2e, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x32,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6e, 0x7a, 0x69, 0x6e, 0x67, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x32, 0x68, 0x61, 0x73, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_g2hasher_proto_rawDescOnce sync.Once
	file_g2hasher_proto_rawDescData = file_g2hasher_proto_rawDesc
)

func file_g2hasher_proto_rawDescGZIP() []byte {
	file_g2hasher_proto_rawDescOnce.Do(func() {
		file_g2hasher_proto_rawDescData = protoimpl.X.CompressGZIP(file_g2hasher_proto_rawDescData)
	})
	return file_g2hasher_proto_rawDescData
}

var file_g2hasher_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_g2hasher_proto_goTypes = []interface{}{
	(*ClearLastExceptionRequest)(nil),    // 0: g2hasher.ClearLastExceptionRequest
	(*ClearLastExceptionResponse)(nil),   // 1: g2hasher.ClearLastExceptionResponse
	(*DestroyRequest)(nil),               // 2: g2hasher.DestroyRequest
	(*DestroyResponse)(nil),              // 3: g2hasher.DestroyResponse
	(*ExportTokenLibraryRequest)(nil),    // 4: g2hasher.ExportTokenLibraryRequest
	(*ExportTokenLibraryResponse)(nil),   // 5: g2hasher.ExportTokenLibraryResponse
	(*GetLastExceptionRequest)(nil),      // 6: g2hasher.GetLastExceptionRequest
	(*GetLastExceptionResponse)(nil),     // 7: g2hasher.GetLastExceptionResponse
	(*GetLastExceptionCodeRequest)(nil),  // 8: g2hasher.GetLastExceptionCodeRequest
	(*GetLastExceptionCodeResponse)(nil), // 9: g2hasher.GetLastExceptionCodeResponse
	(*InitRequest)(nil),                  // 10: g2hasher.InitRequest
	(*InitResponse)(nil),                 // 11: g2hasher.InitResponse
	(*InitWithConfigRequest)(nil),        // 12: g2hasher.InitWithConfigRequest
	(*InitWithConfigResponse)(nil),       // 13: g2hasher.InitWithConfigResponse
	(*ProcessRequest)(nil),               // 14: g2hasher.ProcessRequest
	(*ProcessResponse)(nil),              // 15: g2hasher.ProcessResponse
}
var file_g2hasher_proto_depIdxs = []int32{
	0,  // 0: g2hasher.G2Hasher.ClearLastException:input_type -> g2hasher.ClearLastExceptionRequest
	2,  // 1: g2hasher.G2Hasher.Destroy:input_type -> g2hasher.DestroyRequest
	4,  // 2: g2hasher.G2Hasher.ExportTokenLibrary:input_type -> g2hasher.ExportTokenLibraryRequest
	6,  // 3: g2hasher.G2Hasher.GetLastException:input_type -> g2hasher.GetLastExceptionRequest
	8,  // 4: g2hasher.G2Hasher.GetLastExceptionCode:input_type -> g2hasher.GetLastExceptionCodeRequest
	10, // 5: g2hasher.G2Hasher.Init:input_type -> g2hasher.InitRequest
	12, // 6: g2hasher.G2Hasher.InitWithConfig:input_type -> g2hasher.InitWithConfigRequest
	14, // 7: g2hasher.G2Hasher.Process:input_type -> g2hasher.ProcessRequest
	1,  // 8: g2hasher.G2Hasher.ClearLastException:output_type -> g2hasher.ClearLastExceptionResponse
	3,  // 9: g2hasher.G2Hasher.Destroy:output_type -> g2hasher.DestroyResponse
	5,  // 10: g2hasher.G2Hasher.ExportTokenLibrary:output_type -> g2hasher.ExportTokenLibraryResponse
	7,  // 11: g2hasher.G2Hasher.GetLastException:output_type -> g2hasher.GetLastExceptionResponse
	9,  // 12: g2hasher.G2Hasher.GetLastExceptionCode:output_type -> g2hasher.GetLastExceptionCodeResponse
	11, // 13: g2hasher.G2Hasher.Init:output_type -> g2hasher.InitResponse
	13, // 14: g2hasher.G2Hasher.InitWithConfig:output_type -> g2hasher.InitWithConfigResponse
	15, // 15: g2hasher.G2Hasher.Process:output_type -> g2hasher.ProcessResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_g2hasher_proto_init() }
func file_g2hasher_proto_init() {
	if File_g2hasher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_g2hasher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLastExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearLastExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTokenLibraryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTokenLibraryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastExceptionCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitWithConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitWithConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_g2hasher_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_g2hasher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_g2hasher_proto_goTypes,
		DependencyIndexes: file_g2hasher_proto_depIdxs,
		MessageInfos:      file_g2hasher_proto_msgTypes,
	}.Build()
	File_g2hasher_proto = out.File
	file_g2hasher_proto_rawDesc = nil
	file_g2hasher_proto_goTypes = nil
	file_g2hasher_proto_depIdxs = nil
}
