name: Go test linux - services

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  go-test-linux:
    name: "Go test with OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]

    services:
      servegrpc:
        credentials:
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        env:
          SENZING_TOOLS_ENABLE_ALL: true
          # SENZING_TOOLS_SERVER_CERTIFICATE_PATH: /testdata/certificates/server/certificate.pem
          # SENZING_TOOLS_SERVER_KEY_PATH: /testdata/certificates/server/private_key.pem
        image: senzing/serve-grpc
        options: --user 0
        ports:
          - 8299:8261
        volumes:
          # - ${{ github.workspace }}/testdata:/testdata
          - ./testdata:/testdata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker run
        run: |
          docker run \
            --name servegrpc \
            --rm \
            -d \
            -p 8261:8261 \
            --network ${{ job.container.network }} \
            --user 0 \
            -v ${{ github.workspace }}/testdata:/testdata \
            senzing/serve-grpc

      - name: Docker ps
        uses: docker://docker
        with:
          args: docker ps

      # - name: Copy testdata into docker container
      #   uses: docker://docker
      #   with:
      #     args: docker container exec servegrpc cp -a ${{ github.workspace }}/testdata /

      - name: Restart docker container
        uses: docker://docker
        with:
          args: docker exec servegrpc pwd

      - name: Restart docker container
        uses: docker://docker
        with:
          args: docker exec servegrpc ls -la
