name: Go test linux

on: [push, workflow_dispatch]

env:
  SENZING_LOG_LEVEL: TRACE

permissions:
  contents: read

jobs:
  go-test-linux:
    name: "Go test with OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]

    # services:
    #   servegrpc:
    #     credentials:
    #       password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     env:
    #       SENZING_TOOLS_ENABLE_ALL: true
    #     image: senzing/serve-grpc
    #     options: --user 0
    #     ports:
    #       - 8261:8261

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Docker run
        run: |
          docker run \
            --detach \
            --env SENZING_TOOLS_ENABLE_ALL=true \
            --name servegrpc \
            --publish 8261:8261 \
            --rm \
            senzing/serve-grpc

      - name: Install grpcurl
        run: |
          wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_amd64.deb
          sudo apt-get install -y ./grpcurl_1.9.3_linux_amd64.deb
          grpcurl -version

      - name: Test using grpcurl
        run: |
          grpcurl \
            -format text \
            --insecure \
            localhost:8261 \
              szproduct.SzProduct.GetVersion

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go test
        run: |
          go test -json -v -p 1 -coverprofile=./cover.out -covermode=atomic -coverpkg=./... ./...  2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: cover.out
          path: ./cover.out

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

  coverage:
    name: Coverage
    needs: go-test-linux
    uses: senzing-factory/build-resources/.github/workflows/go-coverage.yaml@v2
    with:
      coverage-config: ./.github/coverage/testcoverage.yaml
